snipsco/snips-nlu

README.rst
docs/source/installation.rst

I added some notes about the `setuptools_rust` / `rust` installation that you need to have before building from sources

Improve installation description

---

cli/cli.py
debug/debug.py
snips_nlu/intent_classifier/featurizer.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/tests/test_intent_classifier_featurizer.py

This PR brings some improvement to the intent classification by leveraging the presence of builtin entities in the training data. 
The strategy consists in preprocessing utterances by looking for builtin entities within the utterances, and add markers for each each entity found while removing the builtin entity substring from the utterance. This allows to capture the fact that a builtin entity is present in an utterance, and prevents from learning specific builtin entities occurence such as `42`.
I have run some intent classification metrics in order to confirm that this improved significantly the performances.

Leverage builtin entities to improve intent classification

---

setup.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/slot_filler/feature_factory.py
snips_nlu/slot_filler/features_utils.py
snips_nlu/tests/test_crf_features.py
snips_nlu/tests/test_features_utils.py

This PR fixes various issues with CRF slot filler features:
- use `get_shape` function from `snips-nlu-utils` in order to avoid discrepancy with the Rust pipeline
- fix a bug which caused the common words gazetteer of the ngram feature to be always `None`
- transform the length feature to a string instead of an int

Fix issues with features

---

snips_nlu/string_variations.py

Entity variation must be limited to a maximum of variations otherwise it can run for a very long time:
- added a `MAX_ENTITY_VARIATIONS` parameters
- for variation functions which generate variation by first computing combination, variations are not computed if the number of combinations are greater than `MAX_ENTITY_VARIATIONS`

Limit the number of combination made in variations

---

setup.py
snips_nlu/builtin_entities.py
snips_nlu/intent_classifier/featurizer.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/nlu_engine/utils.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/slot_filler/feature_factory.py
snips_nlu/string_variations.py

Builtin entity parsing should not be cached unconditionally. Indeed, caching datetime builtin entities is a bad idea as they are often computed relatively to the current context.
Hence, caching is done during train time but deactivated at inference time when resolving values.

Deactivate caching of builtin entity parsing at inference time

---

setup.py
snips_nlu/dataset.py
snips_nlu/intent_classifier/featurizer.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_classifier/log_reg_classifier_utils.py
snips_nlu/slot_filler/features_utils.py
snips_nlu/tests/test_intent_classifier_featurizer.py
snips_nlu/tests/test_log_reg_intent_classifier.py

This PR improves how builtin entities are handled in intent classification at train time and inference time.
*Train time*
Builtin entities values found by the builtin entity parser are not dropped from the training data when they don't correspond to a slot, while slot values are dropped. This prevent from learning specific values such as `tomorrow`, `42`, while keeping other unrelated values such as `morning` (or `night`) in a `GoodMorning` (or `GoodNight`) intent with no slot. 
In both cases, a builtin entity feature using placeholder is used.
*Inference Time*
Builtin entities values found by the builtin entity parser are used in addition to the builtin entity feature.

Improve preprocessing of utterances during intent classification training

---

snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_deterministic_intent_parser.py

We're using a duplicate and erroneous function to compute the mapping from slot name to entity name in the `DeterministicIntentParser`.
If there are two slots with the same name in the input dataset the DeterministicIntentParser only find one of them when parsing.

Fix the creation of slot names to entity mapping

---

snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/pipeline/processing_unit.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_log_reg_intent_classifier.py
snips_nlu/tests/test_probabilistic_intent_parser.py

This allows every processing units, and not only a `SnipsNLUEngine`, to be persisted into (and loaded from) a bytearray:
- `SnipsNLUEngine`
- `DeterministicIntentParser`
- `ProbabilisticIntentParser`
- `CRFSlotFiller`
- `LogRegIntentClassifier`

Add method to persist all processing units into bytearray

---

docs/source/tutorial.rst
snips_nlu/cli/dataset/entities.py
snips_nlu/cli/dataset/examples/entity_location_autoextent_false.txt
snips_nlu/tests/test_cli.py

As discussed in discord and as mentioned in #632, here is a PR allowing to define automatically_extensible property on entities when using the generation tool.
In a txt file representing an entity, if a line contains `# automatically_extensible=false` then the entity will be considered as non extensible

handle automatically_extensible property using dataset generation tool

---

setup.py
tox.ini

Use lowerbound and upperbound for version specifiers when defining dependencies in `setup.py` in order to reduce conflicts between dependencies, and avoid dependency hell.

Make version specifiers of dependencies more flexible

---

snips_nlu/cli/generate_dataset.py
snips_nlu/cli/inference.py
snips_nlu/cli/training.py
snips_nlu/dataset.py
snips_nlu/tests/test_cli.py
snips_nlu/tests/test_dataset.py
snips_nlu/tests/utils.py

When trained on a dataset like the following the synonyms are not mapped correctly:
```python
dataset = {
"intents": {
"dummy_but_tricky_intent": {
"utterances": [
{
"data": [
{
"text": "dummy_value",
"entity": "dummy_but_tricky_entity",
"slot_name": "dummy_but_tricky_slot"
}
]
}
]
}
},
"entities": {
"dummy_but_tricky_entity": {
"data": [
{
"value": "a",
"synonyms": [
"favorïte"
]
},
{
"value": "b",
"synonyms": [
"favorite"
]
}
],
"use_synonyms": True,
"automatically_extensible": False
}
},
"language": "en",
"snips_nlu_version": "0.15.0"
}
```
Indeed the dataset in output of `validate_and_format_dataset` will have the following mapping in the `utterances` section:
```
"favorïte": "a",
"favorite": "a"
```
instead of:
```
"favorïte": "a",
"favorite": "b"
```
This is because we process the …

Fix synonym varitions mapping

---

setup.py

Install enum34 only for Python < 3.4

---

CHANGELOG.md
snips_nlu/__about__.py
snips_nlu/intent_parser/probabilistic_intent_parser.py
snips_nlu/tests/test_probabilistic_intent_parser.py

Fixes https://github.com/snipsco/snips-nlu/issues/656 : 
- Generate a valid crf slot filler file names (files that don't risk to conflict with the OS): `slot_filler_x`

Fix the generation of crf_slot_fillers files names

---

snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/intent_parser/probabilistic_intent_parser.py
snips_nlu/pipeline/configs/intent_parser.py
snips_nlu/pipeline/configs/nlu_engine.py
snips_nlu/pipeline/processing_unit.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_log_reg_intent_classifier.py
snips_nlu/tests/test_probabilistic_intent_parser.py

Remove `unit_name` field from processing unit serialization since it's already persisted in the metadata when the `ProcessingUnit.persist_metadata` method is called

Remove unit_name from processing unit serialization

---

snips_nlu/__main__.py
snips_nlu/cli/download_entity.py
snips_nlu/cli/link.py

- Add a simple CLI to download all the builtin entity resources (gazetteer parsers) by languages, here is an example on how to download all `fr` entity resources:
```
snips-nlu download-language-entities fr
```

Add a CLI to download all builtin entity resources by language

---

snips_nlu/intent_parser/probabilistic_intent_parser.py

- The ProbabilisticIntentParser should set  its `intent_classifier.custom_entity_parser` when it's fitted the same way as the `intent_classifier.builtin_entity_parser`

Correctly set intent classifier custom entity parser in ProbabilisticIntentParser

---

snips_nlu/entity_parser/custom_entity_parser.py
snips_nlu/entity_parser/entity_parser.py

**Description**: Making chatting faster by removing small and big things.
**Checklist**:
Some benchmarks on my workload: (100 runs, but some are "hi" and some are "find intent/slots".
No change::
Removing deepcopy:
As we can see, there are still things that take time just like my last pull request https://github.com/snipsco/snips-nlu/pull/648 like `initial_string_from_tokens()`, `tokens = [c["token"] for c in cache]`, having the hot-path execute last in the functions, using some mutable data structures when they're never modified (and recreating them). This was using a small model, I'll check with big model to see if they take more % time.
What do you think ?

faster chatting (WIP)

---

snips_nlu/cli/metrics.py

- Add a `--config` argument in the metrics CLI
- Replace "parser_threshold" by "matching_strictness" in dataset format
- Optimize loading and inference runtime
- Disable stemming for intent classification in default configs

Fix snips-nlu-metrics import

---

snips_nlu/intent_classifier/log_reg_classifier_utils.py
snips_nlu/pipeline/configs/intent_classifier.py
snips_nlu/tests/test_config.py

- Add the `max_unknown_words` parameter in the `IntentClassifierDataAugmentationConfig` serialization

Fix intent classifier data augmentation configuration serizalization

---

snips_nlu/cli/utils.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/intent_parser/probabilistic_intent_parser.py
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/tests/test_log_reg_intent_classifier.py

- Removed `logging.info()` call that set up an handler for the root logger and ended up in a double logging
- Removed logs that could have been added by the client. Some logs where immediately after the `SnipsNLUEngine` call or just before the `SnipsNLUEngine` output. These logs are useless since they can be added by the caller. They don't log information that's not directly available by the caller and pollute the log output
- Added a debug log to print top activations in the `LogRegIntentClassifier`

Improve logging

---

snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/pipeline/configs/intent_classifier.py
snips_nlu/tests/test_config.py

- `max_unknown_words < 1` in the `IntentClassifierDataAugmentationConfig` makes the data augmentation crash, this should not be allowed

Prevent max_unknown_words < 1

---

snips_nlu/dataset/intent.py
snips_nlu/tests/test_dataset_loading.py
snips_nlu/tests/test_intent_loading.py

This PR fixes an issue when parsing intent utterances from YAML or text file formats, which was first reported [here](https://github.com/snipsco/snips-nlu-metrics/issues/104).
When an utterance contains two consecutive slots separated by a whitespace, then the whitespace is discarded:
```
Show me [ent1:ent1](foo) [ent2:ent2](bar)
```
Gives:
```json
{
"data": [
{
"text": "Show me "
},
{
"entity": "ent1",
"text": "foo",
"slot_name": "ent1"
},
{
"entity": "ent2",
"text": "bar",
"slot_name": "ent2"
}
]
}
```
Instead of:
```json
{
"data": [
{
"text": "Show me "
},
{
"entity": "ent1",
"text": "foo",
"slot_name": "ent1"
},
{
"text": " "
},
{
"entity": "ent2",
"text": "bar",
"slot_name": "ent2"
}
]
}
```
**Checklist**:

Fix bug when generating dataset from YAML and text files

---

snips_nlu/intent_classifier/log_reg_classifier_utils.py
snips_nlu/pipeline/configs/intent_classifier.py
snips_nlu/tests/test_config.py
snips_nlu/tests/test_log_reg_classifier_utils.py

- If `max_unknownwords=None` and `replacement_string` is not `None` the `random_state.randint(1, max_unknown_words + 1)` fails with a `TypeError`
- I fixed the bug and also allowed `max_unknownwords` since it's an intuitive value for the user. If it's 0 then we don't add any unknownword
**Checklist**:

Allow max_unknownwords to be 0 or None

---

docs/source/tutorial.rst
setup.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/intent_parser/probabilistic_intent_parser.py
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/result.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_log_reg_intent_classifier.py
snips_nlu/tests/test_nlu_engine.py
snips_nlu/tests/test_result.py
snips_nlu/tests/utils.py

This PR changes the way the implicit None intent is handled. More specifically, when no intent was found (i.e. when the None intent is found), the parsing output looked like:
```python
{
"input": "foo bar",
"intent": None,
"slots": None
}
```
This was inconsistent compared to the parsing output when an intent was found. Thus this PR changes the parsing output in the case of a None intent to the following:
```python
{
"input": "foo bar",
"intent": {
"intentName": None,
"probability": 0.552122
},
"slots": []
}
```
The `"intent"` value is now ensured to be not None, and a probability is always returned. Besides, the `"slots"` value is now always a list.
**Checklist**:

Return probability of None intent

---

snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/intent_classifier/featurizer.py
snips_nlu/pipeline/configs/intent_classifier.py
snips_nlu/tests/test_config.py
snips_nlu/tests/test_intent_classifier_featurizer.py

- Added a `keep_order` boolean parameter to the `CooccurrenceVectorizerConfig`, when this parameter is `False` we look for unordered cooccurrence while if it's `True` then word order is kept for cooccurrence extraction

Make cooccurrence order configurable

---

snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py

With the improvements that were made in PR https://github.com/snipsco/snips-nlu/pull/717, it now makes sense to improve the value of `"max_queries"` in the default configuration of each language.
This parameter sets the maximum number of utterances that should be kept, per intent, in order to build the regular expressions of the `DeterministicIntentParser`.
Increasing this parameters increases the chances that this parser finds a match. On the other hands, it increases the memory footprints, as we store more patterns, and it increases the time to the `SnipsNLUEngine` object.
**Checklist**:

Increase max_queries from 100 to 500 in default configurations

---

CHANGELOG.md
snips_nlu/cli/metrics.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py

This PR removes a logic that was used in the `CRFSlotFiller` to handle builtin entities. This logic consisted in discarding the builtin tags, as found by the CRF, and instead use the results of the `BuiltinEntityParser` to create possible combinations of builtin slots, and rank those combinations based on the sequence probability given by the CRF.
This logic seems to be the cause of various issues, especially in cases where the span of builtin entities is made ambiguous by the context in the sentence (cf new `CRFSlotFiller` unit test). In such cases, the CRF is pretty good at finding the correct span, and thus the previous logic was detrimental. 
The new logic was benchmarked on a comprehensive list of datasets of various sizes, in various languages. Overall, the F1-score …

Fix handling of builtin entities in CRFSlotFiller

---

snips_nlu/cli/utils.py

Resources can now be referenced without the patch number in the [compatibility file](https://github.com/snipsco/snips-nlu-language-resources/blob/master/compatibility.json).
This avoids to update the compatibility file each time a patch release is made.
**Checklist**:

Fetch resources based only on major and minor

---

snips_nlu/slot_filler/crf_slot_filler.py

The `CRFSlotFillerConfig` passed to the `CRFSlotFiller` when initializing it, is mutated during the training. Thus, it must be deep-copied beforehand to prevent side effects.
**Checklist**:

Fix issue with mutated config

---

snips_nlu/dataset/validation.py
snips_nlu/tests/test_dataset_validation.py

Allows the `matching_strictness` entity property of the dataset to take integer values, on top of float values.
**Checklist**:

Allow matching_strictness property to be int

---

snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/pipeline/configs/intent_parser.py

The stop words resources are actually required by the `DeterministicIntentParser` when `ignore_stop_words` is `True` (stop words must be known to be ignored).
**Checklist**:

Fix issue with resources required by the deterministic intent parser

---

snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_deterministic_intent_parser.py

This fixes an issue when handling and parsing group names in the deterministic intent parser.
**Checklist**:

Fix issue with group names in deterministic parser

---

snips_nlu/cli/inference.py
snips_nlu/common/log_utils.py

- In Python 2.7, UTF-8 `str` input must be converted to `unicode` otherwise we can't type UTF-8 characters in the inference CLI

Fix inference CLI

---

CHANGELOG.md
snips_nlu/__about__.py
snips_nlu/cli/inference.py
snips_nlu/cli/utils.py
snips_nlu/common/log_utils.py
snips_nlu/data_augmentation.py
snips_nlu/dataset/validation.py
snips_nlu/intent_classifier/featurizer.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_classifier/log_reg_classifier_utils.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/pipeline/configs/intent_parser.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py
snips_nlu/tests/test_dataset_validation.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_intent_classifier_featurizer.py
snips_nlu/tests/test_log_reg_classifier_utils.py

- Issue with intent classification reducing classification accuracy
- Issue resulting in a mutation of the CRFSlotFillerConfig
- Wrong required resources of the `DeterministicIntentParser`
- Issue with non ASCII characters when using the parsing CLI with Python2

Release 0.19.3

---

snips_nlu/resources.py
snips_nlu/slot_filler/feature_factory.py

Sort resources alphabetically before persisting them in order to avoid serialization diffs between two trainings.
**Checklist**:

Sort resources before persisting them

---

snips_nlu/cli/download.py

The egg fragment must be `#egg=my_package==version` instead of `#egg=my_package-version`
**Checklist**:

Fix issue with egg fragments in download cli

---

snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/default_configs/config_pt_br.py
snips_nlu/default_configs/config_pt_pt.py
snips_nlu/slot_filler/feature_factory.py
snips_nlu/tests/test_crf_slot_filler.py

This PR fixes an issue which caused a crash when re-fitting a `CRFSlotFiller`.
**Checklist**:

Fix issue when re-fitting slot filler

---

snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_deterministic_intent_parser.py

This PR affects two APIs of the `DeterministicIntentParser`:
- `parse`: when a match is found for several intents, then the `None` intent is returned as there is ambiguity
- `get_intents`: when a match is found for several intents, then the probability is set to `1/len(intents)` for each of the matching intents
**Checklist**:

Improve handling of ambiguous utterances in DeterministicIntentParser

---

snips_nlu/cli/download.py

This avoids silencing underlying symbolic linking errors.
**Checklist**:

Improve failed linking error message after download of resources

---

CHANGELOG.md
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py

Implemented advanced debugging logs for the `CRFSlotFiller`.
Until now debugging the `CRFSlotFiller` decisions was pretty obscure unless you put breakpoints in the code and used some pretty advanced tricks.
I added a log activated in debug level which prints token per token:
- The incoming transitions weights (to the current token label)
- The outgoing transitions weights (from the current token label)
- The token feature weights
- The list of feature extracted from the tokens but which are not in the `CRFSlotFiller` state features (likely not seen at train time)

Implemented advanced log in CRFSlotFiller inference

---

CHANGELOG.md
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/tests/test_nlu_engine.py

The `None` intent was ignored when using the `parse` API in conjunction with `intents` and `top_n`
**Checklist**:

Fixed an issue with the None intent when using the parse top_n API

---

CHANGELOG.md
snips_nlu/intent_classifier/log_reg_classifier.py

The logreg intent classifier used to have a specific logic when used with an intents filter: the intent classification scores were renormalized to sum to 1.0.
This could lead to unexpected behaviors, especially when all the intents in the intents filter are associated to very low confidence scores. In such cases, the renormalization would significantly increase the scores.
**Checklist**:

Remove normalization of confidence scores in intent classification

---

CHANGELOG.md
snips_nlu/__about__.py
snips_nlu/cli/download.py
snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/default_configs/config_pt_br.py
snips_nlu/default_configs/config_pt_pt.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/slot_filler/feature_factory.py
snips_nlu/tests/test_crf_slot_filler.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_nlu_engine.py
tox.ini

- Advanced inference logging in the `CRFSlotFiller` [#776](https://github.com/snipsco/snips-nlu/pull/776)
- Improved failed linking error message after download of resources [#774](https://github.com/snipsco/snips-nlu/pull/774)
- Improve handling of ambiguous utterances in DeterministicIntentParser [#773](https://github.com/snipsco/snips-nlu/pull/773)
- Remove normalization of confidence scores in intent classification [#782](https://github.com/snipsco/snips-nlu/pull/782)
- Fixed a crash due to missing resources when refitting the `CRFSlotFiller` [#771](https://github.com/snipsco/snips-nlu/pull/771)
- Fixed issue with egg fragments in download cli [#769](https://github.com/snipsco/snips-nlu/pull/769)
- Fixed an issue causing the `None` intent to be ignored when using the `parse` API in …

Release 0.19.5

---

snips_nlu/common/utils.py

Avoid redefining future.utils.text_type

---

CHANGELOG.md
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/tests/test_nlu_engine.py

- Raise an error when using unknown intents in intents filter
**Checklist**:

Raise an error when using unknown intents in intents filter

---

CHANGELOG.md
snips_nlu/dataset/utils.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_dataset_utils.py
snips_nlu/tests/test_deterministic_intent_parser.py

The deterministic intent parser skips words that are in the stop words list. However, words that are both in the stop words list and in the list of entity values should not be skipped, and this is the goal of this PR.
**Checklist**:

Fix issue with stop words in DeterministicIntentParser

---

CHANGELOG.md
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_deterministic_intent_parser.py

In some rare cases there can be multiple ambiguous intents. In such cases, priority is given to results containing fewer slots.
**Checklist**:

Re-score ambiguous DeterministicIntentParser results based on slots

---

snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/slot_filler/crf_slot_filler.py

Fitting the following processing units now produces info logs, instead of debug logs:
- `CRFSlotFiller`
- `LogRegIntentClassifier`

Change logging levels from debug to info

---

CHANGELOG.md
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/test_deterministic_intent_parser.py

Ambiguous results (confidence score < 1.0) from the DeterministicIntentParser were systematically discarded. This PR lowers the threshold to 0.5 to allow for slight ambiguities.
**Checklist**:

Accept ambiguous results from DeterministicIntentParser

---

snips_nlu/dataset/validation.py
snips_nlu/string_variations.py
snips_nlu/tests/test_dataset_validation.py
snips_nlu/tests/test_string_variations.py
snips_nlu/tests/utils.py

After analysis generating number entity values variations when validating the dataset can take a very long time when the entity as a lot of value. This is mostly due to running Rustling on each entity value.
To be able to validate the dataset in a reasonable amount of time, number variations are computed only when there are less than 10000 entity values in the entity data.
**Checklist**:

Avoid generating number variations when not needed

---

snips_nlu/dataset/validation.py
snips_nlu/entity_parser/custom_entity_parser.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/string_variations.py
snips_nlu/tests/test_custom_entity_parser.py
snips_nlu/tests/test_dataset_validation.py
snips_nlu/tests/test_string_variations.py

When training the NLU on assistant that have an entity with a large number of values, we noticed the the training time / inference time of the NLU could be majorly impacted.
There were 2 reason for that:
- first, the `CustomEntityParser` which is using a `snips_nlu_parser.GazetteerEntityParser` under the hood, was not making use of `n_gazetteer_stop_words` configuration parameter. Using stopwords when matching value of the gazetteer parser can have a dramatic impact on performances
- secondly when validating the dataset, we generated way to many variations of the same entity value. On some gazetteer we were going from `50k` initial values to `800k` values. Generating a lot of variety in the entity values brings robustness but increase both training and inference time. Moreover the …

Reduce custom entity parser footprint in training time

---

CHANGELOG.md
snips_nlu/dataset/validation.py
snips_nlu/tests/test_dataset_validation.py

When augmenting the dataset, variations of utterance entity values were added without checking possible collisions with other utterance entity values.
**Checklist**:

 Fix possible override of entity values when generating variations

---

snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/default_configs/config_pt_br.py
snips_nlu/default_configs/config_pt_pt.py
snips_nlu/slot_filler/feature_factory.py
snips_nlu/tests/test_crf_features.py

When fitting the `CRFSlotFiller` on a intent, dropout is set once for all entities. However in practice we'd like to have a high dropout for `automatically_extensible` entities (since at inference time, we'll try to parse unseen entity values) and a lower dropout for non `automatically_extensible` entities (since we've seen all of them at training time)
Added the ability to filter entity to which the `CustomEntityMatchFactory` is applied.
This `entity_filter` argument is passed as `args` in the `CustomEntityMatchFactory` configuration.
Currently only one flag can be set in the filter: `automatically_extensible`:
- if `True` then the feature will be computed only for `automatically_extensible` entities
- if `False` the  the feature will be computed only for non …

Filter for entity match feature

---

CHANGELOG.md
snips_nlu/default_configs/config_de.py
snips_nlu/default_configs/config_en.py
snips_nlu/default_configs/config_es.py
snips_nlu/default_configs/config_fr.py
snips_nlu/default_configs/config_it.py
snips_nlu/default_configs/config_ja.py
snips_nlu/default_configs/config_ko.py
snips_nlu/default_configs/config_pt_br.py
snips_nlu/default_configs/config_pt_pt.py
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/pipeline/configs/intent_classifier.py
snips_nlu/tests/test_config.py

This PR introduces a new parameter in the `LogRegIntentClassifierConfig` which is named `noise_reweight_factor`.
This parameter allows to deviate from the default "balanced" class weight strategy by multiplying the Noise class weight by a given factor.
Typically, using `noise_reweight_factor > 1` will end up in a more conservative engine, meaning that it will predict `None` more often, and vice versa.
**Checklist**:

Add noise re-weight factor

---

CHANGELOG.md
setup.py
snips_nlu/dataset/validation.py
snips_nlu/intent_classifier/log_reg_classifier_utils.py
snips_nlu/intent_parser/deterministic_intent_parser.py
snips_nlu/tests/integration_test.py
snips_nlu/tests/test_crf_slot_filler.py
snips_nlu/tests/test_deterministic_intent_parser.py
snips_nlu/tests/test_intent_classifier_featurizer.py
snips_nlu/tests/test_log_reg_classifier_utils.py
snips_nlu/tests/test_log_reg_intent_classifier.py
snips_nlu/tests/test_nlu_engine.py

This fixes an issue when using Python3.5 where training several engines with a fixed `random_state` would not produce identical results.
**Checklist**:

Fix non-deterministic behavior

---

CHANGELOG.md
snips_nlu/intent_classifier/log_reg_classifier.py
snips_nlu/resources.py
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_resources.py

- Add some warning logs
- Raise proper error when attempting to load resources with bad requirements
**Checklist**:

Add warnings and improve errors

---

CHANGELOG.md
snips_nlu/constants.py
snips_nlu/nlu_engine/nlu_engine.py
snips_nlu/tests/test_nlu_engine.py

This PR adds the ability to bypass the model version check which is performed when loading an nlu engine with the `from_path` API:
```python
from snips_nlu import SnipsNLUEngine
engine = SnipsNLUEngine.from_path("path/to/nlu_engine", bypass_version_check=True)
```
The version check is there to ensure compatibility between the loader (the library itself) and the loaded (the trained engine directory/bytes). If the two versions don't match, then an error is raised and the loading is stopped.
The actual incompatibility often depends on the NLU configuration used, which is why it can be useful to disable this check for cases where the trained data is known to be compatible with the new version of the library. In such cases, a warning log will be emitted.
**Checklist**:

Allow to bypass version check

---

CHANGELOG.md
setup.py
snips_nlu/constants.py
snips_nlu/dataset/validation.py
snips_nlu/entity_parser/custom_entity_parser.py
snips_nlu/tests/test_custom_entity_parser.py
snips_nlu/tests/test_dataset_validation.py

In some case the dataset might contain data subject to license terms that need to be placed next to the parsers built from this data.
When fitting the custom entity parser, if the dataset contains license information, the gazetteer entity parser are build with `license_info` (`snips-nlu-parser>=0.3.1`) which ensure that the license will be persisted at the right location when persisting the engine
**Checklist**:

Handle license

---

CHANGELOG.md
setup.py
snips_nlu/cli/utils.py

As specified in the [importlib documentation](https://docs.python.org/3/library/importlib.html#importlib.import_module), the importlib caches must be invalidated after dynamically installing a module.
**Checklist**:

Invalidate importlib caches after dynamically installing module

---

CHANGELOG.md
snips_nlu/dataset/validation.py
snips_nlu/tests/test_custom_entity_parser.py
snips_nlu/tests/test_dataset_validation.py
snips_nlu/tests/utils.py

Allow to fit SnipsNLUEngine with a `Dataset` object.
**Checklist**:

 Allow to fit SnipsNLUEngine with Dataset object

---

CHANGELOG.md
snips_nlu/slot_filler/crf_slot_filler.py
snips_nlu/tests/test_crf_slot_filler.py

Fix filemode of persisted crfsuite files

---

snips_nlu/tests/test_dataset_loading.py

Fixes tests that were failing because of an update of builtin entity examples in the snips_nlu_parsers dependency.
**Checklist**:

Fix yaml dataset loading tests

---

CHANGELOG.md
docs/source/cli.rst
docs/source/quickstart.rst
docs/source/tutorial.rst
snips_nlu/cli/inference.py
snips_nlu/tests/test_cli.py

This PR adds a new parameter in the parsing CLI which allows to provide an intents filter:
```bash
> snips-nlu parse path/to/engine -f intent1,intent3
```
**Checklist**:

Add intents filter parameter in CLI

---

README.rst

There is a small typo in README.rst.
Should read `across` rather than `accross`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, accross -> across
