setup.py
=> Bump snips-nlu-ontology to 0.54.0

AUTHORS.rst, CONTRIBUTING.rst, CONTRIBUTORS.rst, README.rst
Add the following files:
- `AUTHORS.rst`
- `CONTRIBUTING.rst`
Update `README.rst` to reference the contribution guidelines and the license.
=> Make repository comply to open-source standards

cli/cli.py, setup.py
- Sort keys in metrics json in order to make comparisons easier
- Color output of inference cli
=> Improve cli scripts

cli/cli.py, snips_nlu/intent_parser/deterministic_intent_parser.py
This PR fixes an issue in the code responsible for deduplicating regular expressions generated when fitting the `DeterministicIntentParser`.
=> Fix bug with regex deduplication

cli/cli.py
This PR fixes an issue with the inference CLI. The language resources were loaded after loading the engine which caused an error.
=> Fix engine-inference CLI script

docs/source/data_model.rst, docs/source/tutorial.rst
=> minor typos in docs

snips_nlu/intent_classifier/log_reg_classifier.py
This PR improves the calibration of intent classification probabilities. Having calibrated probabilities improves [interpretability](http://scikit-learn.org/stable/modules/calibration.html).
There are two cases:
1) intent classification with no intents filter
The binary logistic regression is naturally well calibrated ([see this for more details](http://qr.ae/TUTh2v)), so what we want is to use One-vs-All probabilities without renormalizing them.
2) intent classification with intents filter
In this case, the prior over intents is no longer uniform as the scope of intents that the input can belong to is reduced. However the logistic regression probabilities, as is, do not leverage this prior information and One-vs-All probabilities are likely to be very poorly calibrated. …
=> Improve calibration of intent classification probabilities

snips_nlu/dataset.py, snips_nlu/nlu_engine/utils.py
- Normalize raw entity values before trying to match them to synonyms
- Strip entity utterances appearing in queries
=> Improve matching of synonyms

snips_nlu/default_configs/config_de.py, snips_nlu/default_configs/config_en.py, snips_nlu/default_configs/config_es.py, snips_nlu/default_configs/config_fr.py, snips_nlu/default_configs/config_ja.py, snips_nlu/default_configs/config_ko.py, snips_nlu/intent_parser/deterministic_intent_parser.py, snips_nlu/pipeline/configs/intent_parser.py, snips_nlu/tests/test_config.py, snips_nlu/tests/test_deterministic_intent_parser.py
- Improve filtering rules when building regex patterns
- Only use builtin entity placeholder when build regex patterns
=> Improve regex patterns in DeterministicIntentParser

setup.py
This should solve https://github.com/snipsco/snips-nlu/issues/605
=> Bump snips-nlu-ontology to 0.57.1

snips_nlu/cli/inference.py
Python2's `input` does an eval, however we want a raw input here.
=> Fix issue with python2 input

setup.py
This update contains several improvements regarding builtin entity parsing, as well as a fix for the bug described in #616
=> Bump snips-nlu-ontology to 0.57.3

README.rst, docs/source/installation.rst
=> Add system requirements

snips_nlu/cli/metrics.py, snips_nlu/intent_classifier/log_reg_classifier.py, snips_nlu/intent_parser/deterministic_intent_parser.py, snips_nlu/intent_parser/probabilistic_intent_parser.py, snips_nlu/nlu_engine/nlu_engine.py, snips_nlu/slot_filler/crf_slot_filler.py, snips_nlu/tests/test_crf_slot_filler.py, snips_nlu/tests/test_deterministic_intent_parser.py, snips_nlu/tests/test_log_reg_intent_classifier.py, snips_nlu/tests/test_nlu_engine.py, snips_nlu/tests/test_probabilistic_intent_parser.py, snips_nlu/tests/utils.py, snips_nlu/utils.py, snips_nlu_samples/sample.py
Optimization: do not train and use CRFs for intents that contain no slots.
=> Optimize slot filling

CHANGELOG.md, snips_nlu/__about__.py, snips_nlu/nlu_engine/utils.py, snips_nlu/tests/test_crf_slot_filler.py, snips_nlu/tests/test_dataset.py, snips_nlu/tests/test_deterministic_intent_parser.py, snips_nlu/tests/test_intent_classifier_featurizer.py, snips_nlu/tests/test_log_reg_intent_classifier.py, snips_nlu/tests/test_nlu_engine.py, snips_nlu/tests/utils.py
- Issue with synonyms when multiple synonyms have the same normalization
=> [HOTFIX] Fix issue with synonyms mapping

README.rst, docs/source/conf.py, setup.py
Python 3.7 is not yet supported
=> Update system requirements

docs/source/cli.rst, docs/source/index.rst, docs/source/tutorial.rst, snips_nlu/__main__.py, snips_nlu/cli/training.py, snips_nlu/cli/utils.py, snips_nlu/tests/test_cli.py
- add documentation about the CLI
- add verbose flag `-v` in `train` command
- add command to print package version: `snips-nlu version`
- add command to print model version: `snips-nlu model-version`
=> Improve CLI

setup.py, snips_nlu/default_configs/config_de.py, snips_nlu/default_configs/config_en.py, snips_nlu/default_configs/config_es.py, snips_nlu/default_configs/config_fr.py, snips_nlu/default_configs/config_it.py
- Disable stemming for intent classification in default configs
=> Update default configs

snips_nlu/cli/metrics.py
**Work done**:
Added the ability to specify a configuration file when running metrics with the CLI
=> Add a --config argument in the metric CLI

snips_nlu/default_configs/config_es.py, snips_nlu/default_configs/config_fr.py, snips_nlu/default_configs/config_it.py
- Put back stemming in default configurations for latin languages
=> Use stemming for latin languages

docs/source/conf.py, docs/source/data_model.rst, docs/source/dataset.rst, setup.py
- Add an important note about special characters in YAML
- Add code tabs to display example both in JSON and YAML
=> Improve documentation

snips_nlu/nlu_engine/nlu_engine.py
This PR fixes an issue when resolving custom entities, and that could result in custom entity values not listed in the dataset.
=> Fix resolution of custom entities

snips_nlu/cli/generate_dataset.py, snips_nlu/cli/inference.py, snips_nlu/tests/test_cli.py, snips_nlu/tests/utils.py, snips_nlu/utils.py
=> Fix CLI issues with unicode

snips_nlu/slot_filler/feature_factory.py
=> Make entity match feature clearer

snips_nlu/common/utils.py, snips_nlu/exceptions.py, snips_nlu/intent_classifier/featurizer.py, snips_nlu/intent_classifier/log_reg_classifier.py, snips_nlu/intent_parser/deterministic_intent_parser.py, snips_nlu/intent_parser/probabilistic_intent_parser.py, snips_nlu/nlu_engine/nlu_engine.py, snips_nlu/pipeline/processing_unit.py, snips_nlu/slot_filler/crf_slot_filler.py, snips_nlu/tests/test_nlu_engine.py
Define specific exceptions for errors raised during loading and persisting.
**Checklist**:
=> Improve error handling when persisting and loading

snips_nlu/default_configs/config_de.py, snips_nlu/default_configs/config_en.py, snips_nlu/default_configs/config_es.py, snips_nlu/default_configs/config_fr.py, snips_nlu/default_configs/config_it.py, snips_nlu/default_configs/config_ja.py, snips_nlu/default_configs/config_ko.py, snips_nlu/pipeline/configs/intent_classifier.py
- Add missing parameters to default configs
- Fix `TfidfVectorizerConfig` required resources
=> Fix default configs

CHANGELOG.md, snips_nlu/__about__.py, snips_nlu/intent_classifier/featurizer.py, snips_nlu/tests/test_intent_classifier_featurizer.py, snips_nlu/tests/test_nlu_engine.py
- Bug causing an unnecessary reloading of shared resources
=> Release 0.19.1

CHANGELOG.md, snips_nlu/__about__.py, snips_nlu/cli/metrics.py, snips_nlu/slot_filler/crf_slot_filler.py, snips_nlu/tests/test_crf_slot_filler.py
- Fix an issue regarding the way builtin entities were handled by the `CRFSlotFiller`
=> Release 0.19.2

CHANGELOG.md, snips_nlu/data_augmentation.py, snips_nlu/intent_classifier/featurizer.py, snips_nlu/intent_classifier/log_reg_classifier.py, snips_nlu/intent_classifier/log_reg_classifier_utils.py, snips_nlu/tests/test_crf_slot_filler.py, snips_nlu/tests/test_intent_classifier_featurizer.py, snips_nlu/tests/test_log_reg_classifier_utils.py
Fixes an issue with intent classification when preprocessing data.
**Checklist**:
=> Fix intent classification issue

docs/source/languages.rst, sample_datasets/beverage_dataset.json, sample_datasets/flights_dataset.json, snips_nlu/intent_parser/deterministic_intent_parser.py, snips_nlu/tests/integration_test.py
This PR improves the inference part of the deterministic parser, by generating better variations of the input. More specifically, each intent is associated to an entity scope (corresponding to all the entities present in the intent), and for each of these scopes a variation of the input is created by replacing the potential entities found by their placeholders.
This makes the deterministic parser more likely to match inputs.
**Checklist**:
=> Improve deterministic parser

snips_nlu/dataset/intent.py, snips_nlu/tests/test_intent_loading.py
=> Improve error message when loading incorrect yaml utterance

snips_nlu/cli/generate_dataset.py
=> Remove deprecated code for generating dataset

.gitignore, CHANGELOG.md, docs/check_doc.sh, docs/source/builtin_entities.rst, docs/source/data_model.rst, docs/source/index.rst, docs/source/languages.rst, docs/write_ontology_doc.py, tox.ini
This will allow to maintain automatically the documentation of:
- supported languages
- supported builtin entities
**Checklist**:
=> Automatically generate documentation for supported languages and builtin entities

CHANGELOG.md, snips_nlu/slot_filler/crf_slot_filler.py, snips_nlu/tests/test_crf_slot_filler.py
fix #806
fix https://forum.snips.ai/t/unable-to-remove-crf-model-file-at-path-permissionerror-13/3437
=> Fix issue when cleaning up crfsuite files

CHANGELOG.md, snips_nlu/__about__.py
- Add intents filter parameter in parsing CLI [#858](https://github.com/snipsco/snips-nlu/pull/858)
- Add documentation about intents filters [#858](https://github.com/snipsco/snips-nlu/pull/858)
- Update dependencies for better python3.8 support [#867](https://github.com/snipsco/snips-nlu/pull/867)
=> Release 0.20.2
